### ISSUE TITLE
sessions with callbackUrl are incorrectly rejected when no JWT is installed

### ISSUE THREAD

**Issue by davidv1992** [privacybydesign/irmago#123]
According to the documentation, specifically (https://irma.app/docs/irma-server/#static-irma-qrs), callbackUrls can be used even when no JWT key is installed, however on irma server version 0.6.1 such requests are rejected anyway.

I would argue this behaviour is also unwanted since there are multiple ways such a setup can be secure even if there is no direct authentication of the irma server on the callback url, most notably urls only reachable from the server and by only using the token from the request and refetching the result from the irma server upon receiving the callback.

**Comment by sietseringers** [comment]
As it turns out, when a session with a `callbackUrl` is started using the static QR feature without having a JWT key installed it will work fine: having a JWT key installed is only enforced when conventionally POSTing a session with a `callbackUrl` to your IRMA server. So that piece of documentation is not actually wrong 😅 

But this inconsistency should not be there, and I agree with you that having a JWT key installed should not be a requirement (even though it might lead to insecure setups). To be honest, I thought I had fixed this long ago but apparently not. We'll fix it.

**Comment by davidv1992** [comment]
I already am planning to make another change tomorrow, so I will just combine this then if you agree.

**Comment by sietseringers** [comment]
That's also fine, thanks.

**Comment by sietseringers** [comment]
After consultation with the team, we decided to do slightly more than just remove the check that a JWT private key is installed: we have introduced a new boolean configuration parameter to the IRMA server that needs to be set to true before the server will accept session requests with a `callbackUrl` if no JWT private key is installed. That way we can require IRMA server admins to think about if what they are doing is safe.

A corresponding update in the documentation will follow.
