### ISSUE TITLE
Irma configuration folder corrupts when exiting irma server during update process

### ISSUE THREAD

**Issue by davidv1992** [privacybydesign/irmago#139]
If an irma server is closed during a scheme update, I can sometimes observe the configuration folder becoming corrupted enough to prevent rebooting of the server in the future. This seems to be related to left-over folders from the update process.

**Comment by sietseringers** [comment]
That's strange, since v0.6.0 there is code that should prevent exactly this from happening, as follows:
* Before downloading new/changed files, make a copy of the scheme
* Update that copy
* After all possible errors have occured, use Go's equivalent of `mv` (which is atomic) to replace the old scheme on disk with the updated copy.

Just to be sure, are you running v0.6.0 or newer?

**Comment by stevenvegt** [comment]
The copy which is made, is made in the same dir as the other schema dirs:
https://github.com/privacybydesign/irmago/blob/0778649dd4b4161e7f473192b68df84b85bdd853/schemes.go#L825-L838
This results in something like  `/data/irma/tempscheme3581524345/irma-demo`

When the move step is somehow not performed, this directory stays persistent.
After a reboot the following code iterates over the folders. It assumes every directory has a `description.xml`. This folder doesn't, it's subfolder do. 

https://github.com/privacybydesign/irmago/blob/0778649dd4b4161e7f473192b68df84b85bdd853/irmaconfig.go#L141-L159

When the file is not found, it throws an error:
https://github.com/privacybydesign/irmago/blob/0778649dd4b4161e7f473192b68df84b85bdd853/internal/common/common.go#L396

I would suggest creating the `tempschemexxxx` folder in the `tmp` dir of the operating system. If the move is not performed, the OS will do the cleanup for us and it will not interfer during the next startup.

**Comment by ivard** [comment]
That sounds like a good solution, although it only works for server applications. The `irmaclient` module also uses this function and this module runs on Android and iOS. That's I think the reason why was chosen for copying within the scheme directory. So if we want to solve this issues for all modules, then it would be better to choose a solution without using `/tmp`.

**Comment by stevenvegt** [comment]
I'm not suggesting `/tmp` but the temporary directory of the os getting it using the [os.TemDir()](https://pkg.go.dev/os#TempDir) call. I have no idea what this does on the iOS and android operating systems.

**Comment by joskuijpers-imec** [comment]
On iOS the temporary directory is sandboxed and does not exist after the app is closed:

https://developer.apple.com/documentation/foundation/filemanager/1407693-url (from https://developer.apple.com/documentation/foundation/1409211-nstemporarydirectory)

**Comment by sietseringers** [comment]
@stevenvegt, thanks for that analysis; indeed that seems to be the problem.

However, I think that unfortunately using `os.TempDir` for these copies will not work. Say the folder where the IRMA schemes live is `/data/irma`, as in your example, so `irma-demo` lives at `/data/irma/irma-demo`. Then the reason that this temporary copy is also written to `/data/irma` is as follows. The scheme update algorithm has to update files within `/data/irma/irma-demo`, but we don't want to do that by directly modifying the contents of `/data/irma/irma-demo`, because we might be interrupted halfway. However, moving a file or folder from one place to another *on the same file system* is generally atomic. Therefore, the update algorithm works as follows:
* put the updated scheme in `/data/irma/tempscheme3581524345/irma-demo`
* move `/data/irma/tempscheme3581524345/irma-demo` to `/data/irma/irma-demo`.
That way, `/data/irma/irma-demo` is always either completely untouched, or completely replaced with the new version.

We need to keep the latter property. But `/tmp`/`os.TempDir` generally lives on a different file system/partition, so the directory moving would no longer be atomic but instead involve copying the entire directory structure. Additionally, I know of no generally available OS-provided function like `os.TempDir` that gives a temporary directory on the same file system as some other directory. Therefore, the only sensible place I can think of to write our updated scheme into is within the schemes path itself, which is the current behaviour.

Instead of using`os.TempDir`, PR #269 solves the issue by:
* Include a dot in the tempdir, i.e. `/data/irma/.tempscheme3581524345`;
* Just before iterating over the schemes within the scheme folder, i.e. `/data/irma`, try to remove any existing `.tempschemeXXXXXXXXXX` folders.
* When iterating over the schemes within the scheme folder, i.e. `/data/irma`, skip folders beginning with a dot. Note that no scheme name can ever contain a dot, so this does not exclude any specific scheme names.
